package com.application.controller.command;

public enum CommandName {
    MAIN,SHOW_MAIN,SHOW_SIGN_IN,SHOW_ERROR_PAGE,
    SHOW_SIGN_UP,LOG_IN,SIGN_UP,ERROR_404,
    SHOW_CONTINUE_SIGN_UP,SHOW_CHECK_MAIL_PAGE,
    CONTINUE_SIGN_UP,LOG_OUT,SHOW_EDIT, EDIT_INFO,
    EDIT_PASSWORD, SHOW_SUCCESS_PASSWORD_PAGE,
    SHOW_EDIT_PASSWORD,SHOW_BOOKING, CONTINUE_BOOKING,
    SHOW_ROOMS,END_BOOKING,APPROVAL_BOOKING, WAIT_APPROVAL_BOOKING,
    SUCCESS_APPROVAL_BOOKING, SHOW_PERSONAL_AREA, SHOW_ADD_HOTEL,
    ADD_HOTEL
}
